spring:
  application:
    name: ms2
#  profiles:
#    active: test
#  cloud:
#    config:
#      uri: http://localhost:8888
  config:
    import: optional:configserver:http://root:s3cr3t@localhost:8888
server:
  port: 8082
book:
  name: Lord Of the Rings
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
