spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: ms1
        uri: lb://ms1
        predicates:
        - Path=/ms1/**
      - id: ms2
        uri: lb://ms2
        predicates:
          - Path=/ms2/**
      - id: ms3
        uri: lb://ms3
        predicates:
          - Path=/ms3/**
